export default function (type: string, data: any) {
  if (type === '猎聘网') {
    return {
      ejobSaveInputVo: {
        "ejobType": "0",
        "ejobId": "",
        "leaCreatetime": "",
        "suggestAppear": false,
        "suggestClick": false,
        "detailIndustrys": "000",
        "ejobJobtitle": '',
        "ejobTitle": data.positionName,
        "detailDutyQualify": `岗位职责：\n${data.responsibilities}\n\n任职要求：\n${data.requirementsText}`,
        "detailTags": "五险一金,年终奖金,带薪年假,年度旅游,定期体检,节日礼物,餐费补贴,通讯津贴",
        "jobSalaryLow": Number(data.lowSalary) * 1000,
        "jobSalaryHigh": Number(data.highSalary) * 10000,
        "ejobSalaryMonth": Number(data.salaryMonth),
        "ejobSalarydiscuss": "0",
        "detailDeptId": "",
        "detailDept": "",
        "detailWorkyearlow": "10",
        "detailWorkyearhigh": "99",
        "detailEdulevel": "050",
        "detailEdulevelTz": "0",
        "detailLanguage": "",
        "detailLanguageOther": 0,
        "ejobFilterapplyflag": "0",
        "shareUsereIds": "",
        "ejobPrivacyreq": "0",
        "ejobAgreementFlag": "1",
        "ejobStudentApplyFlag": "2",
        "letName": "",
        "letId": "",
        "ejobAddressVoList": [
          {
            "ejobDq": "020010010",
            "ejobDqName": "上海-浦东新区",
            "ejobAddress": "上海浦东主题乐园万信酒店",
            "houseNum": "浦东新区",
            "ejobCoordinate": "121.686467,31.169382",
            "subwayCodes": "",
            "businessAreaCodes": "0200095"
          }
        ],
        "receiveEmailVoList": [],
        "detailAbroadExp": [],
        "detailRecruitCnt": data.recruitmentCount,
        "employmentType": "",
        "recruitExpireDate": "1813990449779"
      },
      saveInfoExtVo: {
        "operationStartTime": new Date().getTime(),
        "ejobActionType": "publish",
        "couponId": "",
        "msgId": ""
      }
    }
  }
  if (type === 'boss直聘') {
    return {
      "positionName": data.positionName,
      "description": `岗位职责：\n${data.responsibilities}\n\n任职要求：\n${data.requirementsText}`,
      "positionCategory": data.positionName,
      "position": data.code,
      "jstr": "",
      "comId": "",
      "brandId": "",
      "jobType": "0",
      "experience": "105",
      "degree": "202",
      "lowAge": "0",
      "highAge": "0",
      "lowGraduateYear": "",
      "graduateYear": "",
      "recruitEndTime": "",
      "leastMonth": "0",
      "daysPerWeek": "",
      "partTimeJobJson": "",
      "deadline": "",
      "preferenceJsonStr": "",
      // "relationIdJson": "[{\"addressText\":\"深圳南山区前海大厦-T2栋16\",\"cover\":1,\"encRelationId\":\"a760011dffe3ad581HFy3Ni-EVZZw424UPKY\"}]",
      "workType": "0",
      "workArea": "",
      "phoneAssistantStatus": "0",
      "salaryType": "0",
      "lowSalary": data.lowSalary,
      "highSalary": data.highSalary,
      "salaryMonth": data.salaryMonth,
      "acType": "2501",
      "performance": "",
      "basicSalary": "0",
      "highBasicSalary": "0",
      "salaryDay": "0",
      "socialInsuranceType": "0",
      "socialInsuranceTypeName": "",
      "other": "",
      "probation": "",
      "requireIndustries": "",
      "requireIndustriesDesc": "",
      "acceptOverseas": "0",
      "overseasArea": "",
      "overseasDuration": "",
      "overseasLanguage": "",
      "overseasAddrRelateIds": "",
      "department": "",
      "reportObject": "",
      "anonymous": "0",
      "trainingPlan": "",
      "workday": "0",
      "periodType": "2",
      "period": "",
      "createType": "0",
      "knowBlueIntermediaryTip": "0",
      "proxyType": "0",
      "performanceExplain": "",
      "projectIdStr": "",
      "proxySelfFlag": "true",
      "mustAnonymousType": "0",
      "companyNotConformanceConfirm": "0",
      "geekRequirement": "",
      "partTimeSwitchStatus": "0",
      "partTimeLowSalary": "0",
      "partTimeHighSalary": "0",
      "partTimeSalaryType": "0",
      "encAtsJobId": "",
      "settlementType": "",
      "settlementDetail": "",
      "employmentTime": "",
      "recruitmentCount": "",
      "needProxyCom": "false",
      "hunterPublish": "0",
      "publishScene": "0",
      "direct": "false",
      "spreadCity": "",
      "jobScheme": "true",
      "editFlag": ""
    }
  }
}
